[package]
name = "dwd-api"
version = "0.1.0"
authors = ["Nerixyz <nero.9@hotmail.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["default", "stream"] }
tokio = { version = "0.2", features = ["full"] }
zip = "0.5.8"
serde = { version = "1.0.117", features = ["derive"] }
serde-xml-rs = "0.4.0"
chrono = "0.4.19"
lazy_static = "1.4.0"
maplit = "1.0.2"
serde_json = "1.0.59"
actix-web = "3"
derive_more = {version = "0.99.11", features = [ "error", "display"] }
regex = "1.4.2"
csv = "1.1.5"
