### Get all stations
GET http://localhost:8080/stations
Accept: application/json

### Get the forecast for a given station
GET http://localhost:8080/forecast/{{station}}
Accept: application/json

### Get the report for a given station
GET http://localhost:8080/report/{{station}}
Accept: application/json