name: Formatting

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  CARGO_TERM_COLOR: always

jobs:
  check-rs-format:
    name: Check Formatting (Rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: nightly
      - run: rustup component add rustfmt
      - name: rustfmt
        run: cargo fmt --check

  check-prettier-format:
    name: Check Formatting (Prettier)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting with Prettier
        # Explicit commit, because this isn't tagged yet.
        uses: Nerixyz/actionsx-prettier@94c755de62c501c69236cda12f939d222142cd6d
        with:
          args: -c .
